### ISSUE TITLE
Home Page - Task Database Setup

### ISSUE THREAD

**Issue by khammerm** [COSC481W-2023Fall/planned-out#7]
Database should contain the tasks and their related information such as:

- [x] Task Name
- [x] Task Date
- [x] Task Type
- [x] Details
- [x] Recurring? 

Acceptance Criteria:
If the user enters a task on the home page, the database should store:
- The name of the task
- The date (and time? maybe next sprint)
- What kind of task it is
- A user description of the task
- If the task should be stored for recurring usage, or deleted after completion

**Comment by moorhead212** [comment]
Completed from: 
#12
